### PR TITLE
Add LicenseTemplate.cshtml

### PR DESCRIPTION
**Pull request by daschult**

### CODE REVIEW

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by daschult** [comment]
The only reason at this point is so that I won't accidentally modify the LICENSE.txt files of older Node.js SDK packages. I'm sure we'll turn this on by default in the near future, at which point I can remove the parameter, but for now I'd like to keep it behind a parameter.

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.4.2*

## ❌️ General: 0%

no tests were run for this category


## ✔️ Azure: 100%

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.4.2*

## ❌️ General: 0%

no tests were run for this category


## ✔️ Azure: 100%

**Pull request merged**
