### PR TITLE
added travis yaml file for automation

### PR DESCRIPTION
**Pull request by williexu**

### CODE REVIEW

**Comment by azuresdkci1x** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.3.9*

## General: 98% 

The following 10 features are not covered by your tests:
❌ [`allowedValueEnum`](https://github.com/Azure/autorest.testserver/search?q=allowedValueEnum)
❌ [`expectedEnum`](https://github.com/Azure/autorest.testserver/search?q=expectedEnum)
❌ [`getComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=getComplexPolymorphismComplicated)
❌ [`getEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferenced)
❌ [`getEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferencedConstant)
❌ [`putComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismComplicated)
❌ [`putEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferenced)
❌ [`putEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferencedConstant)
❌ [`roundTripEnum`](https://github.com/Azure/autorest.testserver/search?q=roundTripEnum)
❌ [`unexpectedEnum`](https://github.com/Azure/autorest.testserver/search?q=unexpectedEnum)


## Azure: 99% 

The following 1 features are not covered by your tests:
❌ [`LRONonRetryPut201Creating400InvalidJson`](https://github.com/Azure/autorest.testserver/search?q=LRONonRetryPut201Creating400InvalidJson)

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.3.9*

## General: 98% 

The following 10 features are not covered by your tests:
❌ [`allowedValueEnum`](https://github.com/Azure/autorest.testserver/search?q=allowedValueEnum)
❌ [`expectedEnum`](https://github.com/Azure/autorest.testserver/search?q=expectedEnum)
❌ [`getComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=getComplexPolymorphismComplicated)
❌ [`getEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferenced)
❌ [`getEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferencedConstant)
❌ [`putComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismComplicated)
❌ [`putEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferenced)
❌ [`putEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferencedConstant)
❌ [`roundTripEnum`](https://github.com/Azure/autorest.testserver/search?q=roundTripEnum)
❌ [`unexpectedEnum`](https://github.com/Azure/autorest.testserver/search?q=unexpectedEnum)


## Azure: 99% 

The following 1 features are not covered by your tests:
❌ [`LRONonRetryPut201Creating400InvalidJson`](https://github.com/Azure/autorest.testserver/search?q=LRONonRetryPut201Creating400InvalidJson)

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.3.9*

## General: 98% 

The following 10 features are not covered by your tests:
❌ [`allowedValueEnum`](https://github.com/Azure/autorest.testserver/search?q=allowedValueEnum)
❌ [`expectedEnum`](https://github.com/Azure/autorest.testserver/search?q=expectedEnum)
❌ [`getComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=getComplexPolymorphismComplicated)
❌ [`getEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferenced)
❌ [`getEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferencedConstant)
❌ [`putComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismComplicated)
❌ [`putEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferenced)
❌ [`putEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferencedConstant)
❌ [`roundTripEnum`](https://github.com/Azure/autorest.testserver/search?q=roundTripEnum)
❌ [`unexpectedEnum`](https://github.com/Azure/autorest.testserver/search?q=unexpectedEnum)


## Azure: 99% 

The following 1 features are not covered by your tests:
❌ [`LRONonRetryPut201Creating400InvalidJson`](https://github.com/Azure/autorest.testserver/search?q=LRONonRetryPut201Creating400InvalidJson)

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.3.9*

## General: 98% 

The following 10 features are not covered by your tests:
❌ [`allowedValueEnum`](https://github.com/Azure/autorest.testserver/search?q=allowedValueEnum)
❌ [`expectedEnum`](https://github.com/Azure/autorest.testserver/search?q=expectedEnum)
❌ [`getComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=getComplexPolymorphismComplicated)
❌ [`getEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferenced)
❌ [`getEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferencedConstant)
❌ [`putComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismComplicated)
❌ [`putEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferenced)
❌ [`putEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferencedConstant)
❌ [`roundTripEnum`](https://github.com/Azure/autorest.testserver/search?q=roundTripEnum)
❌ [`unexpectedEnum`](https://github.com/Azure/autorest.testserver/search?q=unexpectedEnum)


## Azure: 99% 

The following 1 features are not covered by your tests:
❌ [`LRONonRetryPut201Creating400InvalidJson`](https://github.com/Azure/autorest.testserver/search?q=LRONonRetryPut201Creating400InvalidJson)

**Comment by azuresdkci1x** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by amarzavery** [comment]
@olydis - We were trying to add travis as well to this repo. Currently the CI fails because of the libunwind issue. 

Can you share what did you do for setting up the linux-x64 CI? This can help us get past this error.

```
> gulp build
[00:04:10] Using gulpfile ~/build/Azure/autorest.nodejs/gulpfile.js
[00:04:10] Starting 'init'...
[00:04:10] Finished 'init' after 394 μs
[00:04:10] Starting 'clear-cache-on-force'...
[00:04:10] Finished 'clear-cache-on-force' after 33 μs
[00:04:10] Starting 'restore'...
[00:04:10] Starting 'version-number'...
[00:04:10] Finished 'version-number' after 47 ms
           /home/travis/build/Azure/autorest.nodejs :: dotnet restore /home/travis/build/Azure/autorest.nodejs/src/autorest.nodejs.csproj /nologo
retrying 1 /home/travis/build/Azure/autorest.nodejs/dotnet restore /home/travis/build/Azure/autorest.nodejs/src/autorest.nodejs.csproj /nologo
Exec Failed /home/travis/build/Azure/autorest.nodejs :: dotnet restore /home/travis/build/Azure/autorest.nodejs/src/autorest.nodejs.csproj /nologo
(stderr)
    Failed to load �}, error: libunwind.so.8: cannot open shared object file: No such file or directory
    Failed to bind to CoreCLR at '/home/travis/.net/2.0.0/node_modules/dotnet-sdk-2.0.0-linux/shared/Microsoft.NETCore.App/2.0.0/libcoreclr.so'
```

**Comment by olydis** [comment]
@amarzavery uhm I did nothing special, just a fresh Ubuntu box with `git` and `node`/`npm`. Maybe the linux version on Travis does not have the required libunwind?

**Comment by olydis** [comment]
ha: https://github.com/Azure/autorest/blob/master/.travis.yml#L6

**Comment by amarzavery** [comment]
@olydis - I see.. That explains it.

@williexu - Can you please add the command to install libunwind in the install section as pointed by Johannes in the above comment.

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.3.9*

## ❌️ General: 98%

<details><summary>10 out of 522 features are not covered by tests</summary><p>

[`allowedValueEnum`](https://github.com/Azure/autorest.testserver/search?q=allowedValueEnum), [`expectedEnum`](https://github.com/Azure/autorest.testserver/search?q=expectedEnum), [`getComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=getComplexPolymorphismComplicated), [`getEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferenced), [`getEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferencedConstant), [`putComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismComplicated), [`putEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferenced), [`putEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferencedConstant), [`roundTripEnum`](https://github.com/Azure/autorest.testserver/search?q=roundTripEnum), [`unexpectedEnum`](https://github.com/Azure/autorest.testserver/search?q=unexpectedEnum)</p></details>

## ❌️ Azure: 99%

<details><summary>1 out of 118 features are not covered by tests</summary><p>

[`LRONonRetryPut201Creating400InvalidJson`](https://github.com/Azure/autorest.testserver/search?q=LRONonRetryPut201Creating400InvalidJson)</p></details>

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.3.9*

## ❌️ General: 98%

<details><summary>10 out of 522 features are not covered by tests</summary><p>

[`allowedValueEnum`](https://github.com/Azure/autorest.testserver/search?q=allowedValueEnum), [`expectedEnum`](https://github.com/Azure/autorest.testserver/search?q=expectedEnum), [`getComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=getComplexPolymorphismComplicated), [`getEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferenced), [`getEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferencedConstant), [`putComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismComplicated), [`putEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferenced), [`putEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferencedConstant), [`roundTripEnum`](https://github.com/Azure/autorest.testserver/search?q=roundTripEnum), [`unexpectedEnum`](https://github.com/Azure/autorest.testserver/search?q=unexpectedEnum)</p></details>

## ❌️ Azure: 99%

<details><summary>1 out of 118 features are not covered by tests</summary><p>

[`LRONonRetryPut201Creating400InvalidJson`](https://github.com/Azure/autorest.testserver/search?q=LRONonRetryPut201Creating400InvalidJson)</p></details>

**Comment by amarzavery** [comment]
@williexu - We also need to say `npm install`. We have mentioned that the language version for node.js is 8.x which is greater than 7.10 (minimum requirement for autorest) and 8.x ships with a npm version greater than 5.4. Hence we don't need to mention the other steps. I believe, simply adding  `- npm install` should work.

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.3.9*

## ❌️ General: 0%

no tests were run for this category


## ❌️ Azure: 0%

no tests were run for this category

**Pull request merged**
