### PR TITLE
Add 'arguments' as a reserved word

### PR DESCRIPTION
**Pull request by ghost**
I noticed some jshint warnings/errors about 'arguments' being a reserved word, so I'm adding it here so that the generator can take care of it for us.

### CODE REVIEW

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Review by RikkiGibson — APPROVED** [review]
No changes from regeneration I imagine?

**Comment by daschult** [comment]
@RikkiGibson Correct. I regenerated, but apparently the testserver doesn't have any schemas with 'arguments' as a parameter name.

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.4.2*

## ❌️ General: 0%

no tests were run for this category


## ✔️ Azure: 100%

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.4.2*

## ❌️ General: 0%

no tests were run for this category


## ✔️ Azure: 100%

**Pull request merged**
