### PR TITLE
Replace GenerateMetadata with GeneratePackageJson and GenerateReadmeMd

### PR DESCRIPTION
**Pull request by ghost**
As we had our discussions about generating complicated README.md files, @amarzavery mentioned that we would still want to generate a package.json file. This made sense to me, so this PR replaces the GenerateMetadata parameter with GeneratePackageJson and GenerateReadmeMd.

### CODE REVIEW

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.4.2*

## ❌️ General: 0%

no tests were run for this category


## ✔️ Azure: 100%

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.4.2*

## ❌️ General: 0%

no tests were run for this category


## ✔️ Azure: 100%

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.4.2*

## ❌️ General: 0%

no tests were run for this category


## ✔️ Azure: 100%

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.4.2*

## ❌️ General: 0%

no tests were run for this category


## ✔️ Azure: 100%

**Comment by daschult** [comment]
@amarzavery @RikkiGibson Can one of you sign on this PR?

**Review by RikkiGibson — APPROVED** [review]
Gulp can deal with large numbers of regenerate tasks now, right?

**Comment by daschult** [comment]
@RikkiGibson What do you mean?

**Comment by RikkiGibson** [comment]
I recall in the past some kind of timeout issue that necessitated running the gulp tasks in serial order or creating a standalone script to run the tasks one by one.

**Comment by daschult** [comment]
Oh, yeah. I solved that problem a while ago. It turned out that I didn't have the latest version of AutoRest. Once I updated my AutoRest version, everything worked fine.

**Pull request merged**
